#!/bin/sh
set -e -x

sed -i "s/our \$pi_zone.*/our \$pi_zone                    = \'${MESH_ID}\';/" /usr/lib/cgi-bin/meshchatconfig.pm

sed -i "s/our \$local_meshchat_node.*/our \$local_meshchat_node        = \'${NODE_ID}';/" /usr/lib/cgi-bin/meshchatconfig.pm

#sed -i "s/        return lc(\$hostname);/        return lc(\"$NODE_ID\");/" /usr/lib/cgi-bin/meshchatlib.pm

apachectl -DFOREGROUND "$@"
